### ISSUE TITLE
making build

### ISSUE THREAD

**Issue by chetan-northout** [SwapyNetwork/electron-metamask-boilerplate#7]
Uncaught Exception:
TypeError: Cannot read property 'load' of undefined
    at /tmp/.mount_firstB5axfdY/resources/app.asar/extensions.js:21:38
    at ELECTRON_ASAR.js:500:9
    at FSReqWrap.wrapper [as oncomplete] (fs.js:664:17)

**Comment by icaroharry** [comment]
Hi. Were you able to solve this?

It seems that it's a misconfiguration in your build, but I'm not sure what it is. Can you provide more details on the context?

**Comment by chetan-northout** [comment]
I am also facing same issue
